open-feature/playground

packages/openfeature-js/src/lib/types.ts
=> Fixed variation response types

.env.example, package-lock.json, package.json, packages/api/project.json, packages/js-launchdarkly-provider/.eslintrc.json, packages/js-launchdarkly-provider/README.md, packages/js-launchdarkly-provider/jest.config.js, packages/js-launchdarkly-provider/package.json, packages/js-launchdarkly-provider/project.json, packages/js-launchdarkly-provider/src/index.ts, packages/js-launchdarkly-provider/src/lib/js-launchdarkly-provider.ts, packages/js-launchdarkly-provider/tsconfig.json, packages/js-launchdarkly-provider/tsconfig.lib.json, packages/js-launchdarkly-provider/tsconfig.spec.json, packages/openfeature-js/src/lib/api.ts, scripts/launchdarkly-demo.js, tsconfig.base.json, workspace.json
Adds demo LaunchDarkly demo provider
=> Add LaunchDarkly demo provider

package-lock.json, package.json, packages/api/src/hello-markup.ts, packages/api/src/install-markup.ts, packages/api/src/install-template.ts, packages/api/src/main.ts, packages/api/src/types.ts, packages/openfeature-extra/src/index.ts, packages/openfeature-extra/src/lib/hooks/class-validator-hook.ts
A small demo for getting an object flag and adding a customer attribute.
=> Add object/attribute demo

tools/generators/provider-generator/files/provider/src/lib/__fileName__.ts__tmpl__, tools/generators/provider-generator/index.ts
Fix generator after recent updates.
=> Fix generator references

.gitignore, flags.json.example, package.json, packages/app/project.json, packages/js-json-provider/.babelrc, packages/js-json-provider/.eslintrc.json, packages/js-json-provider/README.md, packages/js-json-provider/jest.config.js, packages/js-json-provider/package.json, packages/js-json-provider/project.json, packages/js-json-provider/src/index.ts, packages/js-json-provider/src/lib/json.spec.ts, packages/js-json-provider/src/lib/json.ts, packages/js-json-provider/tsconfig.json, packages/js-json-provider/tsconfig.lib.json, packages/js-json-provider/tsconfig.spec.json, packages/openfeature-js/src/lib/types.ts, scripts/json-demo.js, tsconfig.base.json, workspace.json
Adding simple JSON file provider.
This will be used in the new dynamic demo UI.
=> Add json provider

README.md, packages/app/src/app/fibonacci-as-a-service.controller.ts, packages/app/src/app/hex-color/hex-color.service.ts
- fixing bad links
- mentioning UI demo in provider demos
- adding new heading and links to provider demos
=> Update README with new demos

package.json
=> Remove extra ghcr image name

.github/workflows/release-please.yml
=> fix: disable multi-arch build

.github/workflows/release-please.yml
=> fix: disable QEMU

docker-compose.yaml, release-please-config.json
=> feat: use image in docker compose

packages/ui/src/main.tsx
Addresses grammatical issues discovered in the tutorial.
Fixes #74
=> fix: address grammatical issues discovered in the tutorial

README.md
=> chore: move provider configurations under collapsible sections

release-please-config.json
The pre-major logic doesn't make sense in the playground.
=> chore: remove pre-major override in release please

.github/workflows/ci.yml, .github/workflows/release-please.yml
=> fix: bump ci step versions

packages/fibonacci-service/src/app/auth.guard.ts
=> fix: disable auth in fib service when env var aren't defined

README.md
=> docs: update overview of Flagsmith

packages/fibonacci-service/src/app/auth.guard.ts
=> fix: auth guard returns proper error code

README.md
=> docs: update overview of LaunchDarkly

docker-compose.yaml
=> chore: bump flagd version

package-lock.json, package.json, packages/app/src/app/app.module.ts, packages/app/src/app/open-feature.logger.ts, packages/app/src/app/provider.service.ts, packages/app/src/main.ts, packages/fibonacci-service/src/app/app.module.ts, packages/fibonacci-service/src/main.ts, packages/fibonacci/src/lib/fibonacci.ts, packages/js-flagsmith-provider/src/lib/flagsmith.ts, packages/js-harness-provider/src/lib/js-harness-provider.ts, packages/js-launchdarkly-provider/src/lib/js-launchdarkly-provider.ts, packages/js-split-provider/src/lib/js-split-provider.ts, packages/openfeature-extra/src/lib/hooks/logging-hook.ts
- adds pino logger
Setting the environment variable `NODE_ENV` to `production` enables JSON logging.
=> feat: add pino logger support

packages/openfeature-extra/src/lib/hooks/logging-hook.ts
=> fix: openfeature hook log level

packages/ui/src/app/app.tsx, packages/ui/src/app/calculator.tsx
Shows and error if there's an error in fib calculation:
Closes: https://github.com/open-feature/playground/issues/122
=> feat: show error icon on calc error

package-lock.json, package.json
=> fix: revert otel hook to the span based version

config/k8s/end-to-end.yaml
Signed-off-by: James Milligan <james@omnant.co.uk>
- updated deprecated annotation `openfeature.dev` to `openfeature.dev/enabled`
=> chore: updated deprecated annotation

packages/app/Dockerfile, packages/fibonacci-service/Dockerfile
This fixes all the critical CVEs in the org.
=> fix: use more secure images

docker-compose.yaml
- enable all cors origins in flagd
=> feat: enable all cors origins in flagd

.github/workflows/ci.yml
=> ci: add cache to ci job

package.json
- update license in package.json
The package.json and the repo had different licenses. Updating the package.json license to be consistent.
=> docs: update license in package json

README.md
- update links
- fix typos
Fixes #233
=> docs: update links and fix typos

package-lock.json, package.json, packages/app/project.json, packages/app/src/app/app.module.ts
=> chore: update to tracing hook, fix nx:serve

docker-compose.yaml
@beeme1mr I did not get to remove the wrong docker-compose lines before #273 was merged.
This fixes it.
=> fix: docker-compose.yaml image instead of build

package-lock.json, package.json
Overrides to force transitive dependency versions and fix reported vulnerabilities [1]
[1] - https://github.com/open-feature/playground/security/dependabot
=> fix: overrides to fix vulnerabilities
